name: test

on:
  pull_request:
    branches:
      - main
      - dev

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Main checkout
        uses: actions/checkout@v3

      - name: Checkout private accounts-v2
        uses: actions/checkout@v3
        with:
          repository: arcadia-finance/accounts-v2
          ssh-key: ${{ secrets.ACCOUNT_V2_DEPLOY_KEY }}

      - name: Submodule checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run format
        run: forge fmt --check

      # - name: Run Forge build
      #   run: |
      #     forge --version
      #     forge build --sizes
      #   id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
